model:
  model_id: "TheBloke/Mistral-7B-Instruct-v0.2-GGUF"
  temperature: 0.7
  max_tokens: 2048

agent:
  mode: "approval"  # or "autonomous"
  max_iterations: 50

filesystem:
  max_file_size_mb: 10
  backup_enabled: true

executor:
  timeout_seconds: 30
  sandbox_enabled: true